# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTYOPrMsXgIoyWxelQCZ-uygNCjdkrYo
"""

i=1
while i <=100:
  print(i)
  i+=1

i=10
while i >=1:
  print(i)
  i-=1

i=1
m=int(input("enter the number n"))
while i <=10:
  print(m*i)
  i+=1

list=[1,4,9,16,25,36,49,64,81,100]
idx=0
for i in list:
  if(i==36):
    print("found at index",idx)
  idx+=1

for i in range(1,11,1):
    print(i)

for i in range(10,0,-1):
  print(i)

n=int(input('enter the number:'))
i=1
while i <=10:
  print(n*i)
  i+=1

n=int(input('enter the number:'))
for i in range(1,11):
  print(n*i)

n=int(input('enter the number:'))

i=1
sum=0
while i <=n:


  i+=1
  print("sum =",sum)

n=int(input("enter the number:"))
sum=n * ((n+1)/2)
print(sum)

list=[1,2,3,4,5]
def len_list(list):
  print(len(list))

len_list(list)

list=[1,2,3,4,5]
def len_list():
  for i in list:
    print(i,end=" ")



len_list()

def fact(n):
    factorial = 1
    for i in range(1, n + 1):
        factorial = factorial * i
    print(factorial)

fact(5)

class Student:
  name="shifa"

s1=Student()
print(s1)

class Student:
  name="shifa"

s1=Student()
print(s1.name)

class Car:
  name="swift"

c1=Car()
print(c1.name)

class Student:
  def __init__(self,name,marks):
    self.name=name
    self.marks=marks

s1=Student("shifa", 99)
print(s1.name)
print(s1.marks)

class Student():
    def __init__(self,name,marks1,marks2,marks3):
        self.name=name
        self.marks1=marks1
        self.marks2=marks2
        self.marks3=marks3


    def get_avg(self):
      avg=(self.marks1+self.marks2+self.marks3)/3
      print("student name:",self.name)
      print("averagemarks:",avg)


s1=Student("karan",55,77,88)
s1.get_avg()

